// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infoblox/storage/v1/storage.proto

// Package infoblox.storage.v1 declares engine-neutral, storage-layer annotations
// for API resource messages. The options carry no ORM/engine specifics (canonical
// policy forbids those in a published schema) — they are neutral, API-meaningful
// references that downstream code generators consume to wire persistence.

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_infoblox_storage_v1_storage_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50050,
		Name:          "infoblox.storage.v1.model",
		Tag:           "bytes,50050,opt,name=model",
		Filename:      "infoblox/storage/v1/storage.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// model binds this resource message to a backing storage model, so several API
	// surfaces can project the SAME stored entity (e.g. v1.Coupon, v2.Coupon, and an
	// admin view all backed by one "Coupon" model). When the value differs from the
	// message name, the message is a projection/surface over that model rather than a
	// model of its own. Absent (the common case) means the model is the message name
	// itself.
	//
	// optional string model = 50050;
	E_Model = &file_infoblox_storage_v1_storage_proto_extTypes[0]
)

var File_infoblox_storage_v1_storage_proto protoreflect.FileDescriptor

const file_infoblox_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"!infoblox/storage/v1/storage.proto\x12\x13infoblox.storage.v1\x1a google/protobuf/descriptor.proto:7\n" +
	"\x05model\x12\x1f.google.protobuf.MessageOptions\x18\x82\x87\x03 \x01(\tR\x05modelBBZ@github.com/infobloxopen/apis/proto/infoblox/storage/v1;storagev1b\x06proto3"

var file_infoblox_storage_v1_storage_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_infoblox_storage_v1_storage_proto_depIdxs = []int32{
	0, // 0: infoblox.storage.v1.model:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infoblox_storage_v1_storage_proto_init() }
func file_infoblox_storage_v1_storage_proto_init() {
	if File_infoblox_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infoblox_storage_v1_storage_proto_rawDesc), len(file_infoblox_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_infoblox_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_infoblox_storage_v1_storage_proto_depIdxs,
		ExtensionInfos:    file_infoblox_storage_v1_storage_proto_extTypes,
	}.Build()
	File_infoblox_storage_v1_storage_proto = out.File
	file_infoblox_storage_v1_storage_proto_goTypes = nil
	file_infoblox_storage_v1_storage_proto_depIdxs = nil
}
