// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: infoblox/field/v1/field.proto

package fieldv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldOptions declares field-level data-modeling properties: sensitivity,
// storage constraints, and relationships. This is intentionally separate from
// the authz package — secret fields and ORM associations are data concerns,
// not authorization concerns.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secret marks a field as sensitive. The framework will:
	//   - never store the plaintext value (hash + optional cipher only),
	//   - redact the value in logs ("[REDACTED]"),
	//   - reject any Get/List response that returns a non-empty value.
	Secret bool `protobuf:"varint,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Storage constraints.
	NotNull    bool   `protobuf:"varint,2,opt,name=not_null,json=notNull,proto3" json:"not_null,omitempty"`         // DB NOT NULL constraint
	Unique     bool   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`                          // DB UNIQUE constraint / uniqueIndex
	Index      bool   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`                            // DB index (non-unique)
	ColumnName string `protobuf:"bytes,5,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"` // override the default snake_case column name
	ColumnType string `protobuf:"bytes,6,opt,name=column_type,json=columnType,proto3" json:"column_type,omitempty"` // override the DB column type (e.g. "varchar(255)")
	// Relationships. Declare on the proto field that holds the related resource.
	// The codegen plugins generate the appropriate ORM association or graph edge.
	HasOne        *HasOne     `protobuf:"bytes,20,opt,name=has_one,json=hasOne,proto3" json:"has_one,omitempty"`
	HasMany       *HasMany    `protobuf:"bytes,21,opt,name=has_many,json=hasMany,proto3" json:"has_many,omitempty"`
	BelongsTo     *BelongsTo  `protobuf:"bytes,22,opt,name=belongs_to,json=belongsTo,proto3" json:"belongs_to,omitempty"`
	ManyToMany    *ManyToMany `protobuf:"bytes,23,opt,name=many_to_many,json=manyToMany,proto3" json:"many_to_many,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_infoblox_field_v1_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_field_v1_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_infoblox_field_v1_field_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *FieldOptions) GetNotNull() bool {
	if x != nil {
		return x.NotNull
	}
	return false
}

func (x *FieldOptions) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *FieldOptions) GetIndex() bool {
	if x != nil {
		return x.Index
	}
	return false
}

func (x *FieldOptions) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *FieldOptions) GetColumnType() string {
	if x != nil {
		return x.ColumnType
	}
	return ""
}

func (x *FieldOptions) GetHasOne() *HasOne {
	if x != nil {
		return x.HasOne
	}
	return nil
}

func (x *FieldOptions) GetHasMany() *HasMany {
	if x != nil {
		return x.HasMany
	}
	return nil
}

func (x *FieldOptions) GetBelongsTo() *BelongsTo {
	if x != nil {
		return x.BelongsTo
	}
	return nil
}

func (x *FieldOptions) GetManyToMany() *ManyToMany {
	if x != nil {
		return x.ManyToMany
	}
	return nil
}

// HasOne declares a one-to-one relationship where the foreign key lives on the
// associated model's table. Annotate the message-typed field that holds the
// associated resource (e.g. User.CreditCard where credit_cards.user_id is the FK).
type HasOne struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// foreign_key is the column name on the associated table.
	ForeignKey string `protobuf:"bytes,1,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	// association_foreign_key is the column on this table (default: primary key).
	AssociationForeignKey string `protobuf:"bytes,2,opt,name=association_foreign_key,json=associationForeignKey,proto3" json:"association_foreign_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HasOne) Reset() {
	*x = HasOne{}
	mi := &file_infoblox_field_v1_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasOne) ProtoMessage() {}

func (x *HasOne) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_field_v1_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasOne.ProtoReflect.Descriptor instead.
func (*HasOne) Descriptor() ([]byte, []int) {
	return file_infoblox_field_v1_field_proto_rawDescGZIP(), []int{1}
}

func (x *HasOne) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *HasOne) GetAssociationForeignKey() string {
	if x != nil {
		return x.AssociationForeignKey
	}
	return ""
}

// HasMany declares a one-to-many relationship where the FK is on the
// associated table. Annotate the repeated message-typed field.
type HasMany struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ForeignKey            string                 `protobuf:"bytes,1,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	AssociationForeignKey string                 `protobuf:"bytes,2,opt,name=association_foreign_key,json=associationForeignKey,proto3" json:"association_foreign_key,omitempty"`
	// position_field enables ordered has_many (e.g. for ranked items).
	PositionField string `protobuf:"bytes,3,opt,name=position_field,json=positionField,proto3" json:"position_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasMany) Reset() {
	*x = HasMany{}
	mi := &file_infoblox_field_v1_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasMany) ProtoMessage() {}

func (x *HasMany) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_field_v1_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasMany.ProtoReflect.Descriptor instead.
func (*HasMany) Descriptor() ([]byte, []int) {
	return file_infoblox_field_v1_field_proto_rawDescGZIP(), []int{2}
}

func (x *HasMany) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *HasMany) GetAssociationForeignKey() string {
	if x != nil {
		return x.AssociationForeignKey
	}
	return ""
}

func (x *HasMany) GetPositionField() string {
	if x != nil {
		return x.PositionField
	}
	return ""
}

// BelongsTo declares the inverse side of a has_one or has_many: the FK lives
// on this table. Annotate the message-typed field that holds the parent.
type BelongsTo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// foreign_key is the column on THIS table (e.g. "user_id" on orders).
	ForeignKey            string `protobuf:"bytes,1,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	AssociationForeignKey string `protobuf:"bytes,2,opt,name=association_foreign_key,json=associationForeignKey,proto3" json:"association_foreign_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BelongsTo) Reset() {
	*x = BelongsTo{}
	mi := &file_infoblox_field_v1_field_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BelongsTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BelongsTo) ProtoMessage() {}

func (x *BelongsTo) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_field_v1_field_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BelongsTo.ProtoReflect.Descriptor instead.
func (*BelongsTo) Descriptor() ([]byte, []int) {
	return file_infoblox_field_v1_field_proto_rawDescGZIP(), []int{3}
}

func (x *BelongsTo) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *BelongsTo) GetAssociationForeignKey() string {
	if x != nil {
		return x.AssociationForeignKey
	}
	return ""
}

// ManyToMany declares a many-to-many relationship via an explicit join table.
type ManyToMany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// join_table is the name of the join table.
	JoinTable string `protobuf:"bytes,1,opt,name=join_table,json=joinTable,proto3" json:"join_table,omitempty"`
	// foreign_key is this model's FK column in the join table.
	ForeignKey string `protobuf:"bytes,2,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	// association_foreign_key is the other model's FK column in the join table.
	AssociationForeignKey string `protobuf:"bytes,3,opt,name=association_foreign_key,json=associationForeignKey,proto3" json:"association_foreign_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ManyToMany) Reset() {
	*x = ManyToMany{}
	mi := &file_infoblox_field_v1_field_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManyToMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyToMany) ProtoMessage() {}

func (x *ManyToMany) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_field_v1_field_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyToMany.ProtoReflect.Descriptor instead.
func (*ManyToMany) Descriptor() ([]byte, []int) {
	return file_infoblox_field_v1_field_proto_rawDescGZIP(), []int{4}
}

func (x *ManyToMany) GetJoinTable() string {
	if x != nil {
		return x.JoinTable
	}
	return ""
}

func (x *ManyToMany) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *ManyToMany) GetAssociationForeignKey() string {
	if x != nil {
		return x.AssociationForeignKey
	}
	return ""
}

var file_infoblox_field_v1_field_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50003,
		Name:          "infoblox.field.v1.opts",
		Tag:           "bytes,50003,opt,name=opts",
		Filename:      "infoblox/field/v1/field.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// opts carries all field-level data-modeling properties.
	// Extension number 50003 (alongside method-level rule = 50001 in authz).
	//
	// optional infoblox.field.v1.FieldOptions opts = 50003;
	E_Opts = &file_infoblox_field_v1_field_proto_extTypes[0]
)

var File_infoblox_field_v1_field_proto protoreflect.FileDescriptor

const file_infoblox_field_v1_field_proto_rawDesc = "" +
	"\n" +
	"\x1dinfoblox/field/v1/field.proto\x12\x11infoblox.field.v1\x1a google/protobuf/descriptor.proto\"\x9a\x03\n" +
	"\fFieldOptions\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\bR\x06secret\x12\x19\n" +
	"\bnot_null\x18\x02 \x01(\bR\anotNull\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x14\n" +
	"\x05index\x18\x04 \x01(\bR\x05index\x12\x1f\n" +
	"\vcolumn_name\x18\x05 \x01(\tR\n" +
	"columnName\x12\x1f\n" +
	"\vcolumn_type\x18\x06 \x01(\tR\n" +
	"columnType\x122\n" +
	"\ahas_one\x18\x14 \x01(\v2\x19.infoblox.field.v1.HasOneR\x06hasOne\x125\n" +
	"\bhas_many\x18\x15 \x01(\v2\x1a.infoblox.field.v1.HasManyR\ahasMany\x12;\n" +
	"\n" +
	"belongs_to\x18\x16 \x01(\v2\x1c.infoblox.field.v1.BelongsToR\tbelongsTo\x12?\n" +
	"\fmany_to_many\x18\x17 \x01(\v2\x1d.infoblox.field.v1.ManyToManyR\n" +
	"manyToMany\"a\n" +
	"\x06HasOne\x12\x1f\n" +
	"\vforeign_key\x18\x01 \x01(\tR\n" +
	"foreignKey\x126\n" +
	"\x17association_foreign_key\x18\x02 \x01(\tR\x15associationForeignKey\"\x89\x01\n" +
	"\aHasMany\x12\x1f\n" +
	"\vforeign_key\x18\x01 \x01(\tR\n" +
	"foreignKey\x126\n" +
	"\x17association_foreign_key\x18\x02 \x01(\tR\x15associationForeignKey\x12%\n" +
	"\x0eposition_field\x18\x03 \x01(\tR\rpositionField\"d\n" +
	"\tBelongsTo\x12\x1f\n" +
	"\vforeign_key\x18\x01 \x01(\tR\n" +
	"foreignKey\x126\n" +
	"\x17association_foreign_key\x18\x02 \x01(\tR\x15associationForeignKey\"\x84\x01\n" +
	"\n" +
	"ManyToMany\x12\x1d\n" +
	"\n" +
	"join_table\x18\x01 \x01(\tR\tjoinTable\x12\x1f\n" +
	"\vforeign_key\x18\x02 \x01(\tR\n" +
	"foreignKey\x126\n" +
	"\x17association_foreign_key\x18\x03 \x01(\tR\x15associationForeignKey:T\n" +
	"\x04opts\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\v2\x1f.infoblox.field.v1.FieldOptionsR\x04optsB>Z<github.com/infobloxopen/apis/proto/infoblox/field/v1;fieldv1b\x06proto3"

var (
	file_infoblox_field_v1_field_proto_rawDescOnce sync.Once
	file_infoblox_field_v1_field_proto_rawDescData []byte
)

func file_infoblox_field_v1_field_proto_rawDescGZIP() []byte {
	file_infoblox_field_v1_field_proto_rawDescOnce.Do(func() {
		file_infoblox_field_v1_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infoblox_field_v1_field_proto_rawDesc), len(file_infoblox_field_v1_field_proto_rawDesc)))
	})
	return file_infoblox_field_v1_field_proto_rawDescData
}

var file_infoblox_field_v1_field_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_infoblox_field_v1_field_proto_goTypes = []any{
	(*FieldOptions)(nil),              // 0: infoblox.field.v1.FieldOptions
	(*HasOne)(nil),                    // 1: infoblox.field.v1.HasOne
	(*HasMany)(nil),                   // 2: infoblox.field.v1.HasMany
	(*BelongsTo)(nil),                 // 3: infoblox.field.v1.BelongsTo
	(*ManyToMany)(nil),                // 4: infoblox.field.v1.ManyToMany
	(*descriptorpb.FieldOptions)(nil), // 5: google.protobuf.FieldOptions
}
var file_infoblox_field_v1_field_proto_depIdxs = []int32{
	1, // 0: infoblox.field.v1.FieldOptions.has_one:type_name -> infoblox.field.v1.HasOne
	2, // 1: infoblox.field.v1.FieldOptions.has_many:type_name -> infoblox.field.v1.HasMany
	3, // 2: infoblox.field.v1.FieldOptions.belongs_to:type_name -> infoblox.field.v1.BelongsTo
	4, // 3: infoblox.field.v1.FieldOptions.many_to_many:type_name -> infoblox.field.v1.ManyToMany
	5, // 4: infoblox.field.v1.opts:extendee -> google.protobuf.FieldOptions
	0, // 5: infoblox.field.v1.opts:type_name -> infoblox.field.v1.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_infoblox_field_v1_field_proto_init() }
func file_infoblox_field_v1_field_proto_init() {
	if File_infoblox_field_v1_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infoblox_field_v1_field_proto_rawDesc), len(file_infoblox_field_v1_field_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_infoblox_field_v1_field_proto_goTypes,
		DependencyIndexes: file_infoblox_field_v1_field_proto_depIdxs,
		MessageInfos:      file_infoblox_field_v1_field_proto_msgTypes,
		ExtensionInfos:    file_infoblox_field_v1_field_proto_extTypes,
	}.Build()
	File_infoblox_field_v1_field_proto = out.File
	file_infoblox_field_v1_field_proto_goTypes = nil
	file_infoblox_field_v1_field_proto_depIdxs = nil
}
